name: identity-keycloak

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${DB_DATABASE:-keycloak}
      KC_DB_USERNAME: ${DB_USER:-keycloak}
      KC_DB_PASSWORD: ${DB_PASSWORD:-keycloak_secure_pass}
      KEYCLOAK_ADMIN: ${ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin_secure_pass}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: "edge"
    ports:
      - "8484:8080"
    depends_on:
      - keycloak-db
    restart: unless-stopped

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-keycloak}
      POSTGRES_USER: ${DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-keycloak_secure_pass}
    volumes:
      - ./config/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
