from __future__ import annotations
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from .security import SecurityLevel


class AgentRole(str, Enum):
    SECOPS_HUNTER = "secops_threat_hunter"
    SYSADMIN_OPTIMIZER = "sysadmin_optimizer"
    SMART_HOME_ENERGY = "smart_home_energy"
    PREDICTIVE_HEALER = "predictive_healer"
    NETSEC = "netsec_agent"
    INFRA = "infra_agent"
    STORAGE = "storage_agent"
    HOME = "home_agent"
    SWARM_ORCHESTRATOR = "swarm_orchestrator"


class SubAgentTask(BaseModel):
    """Task delegated to a specialized sub-agent."""
    task_id: str
    role: AgentRole
    objective: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    security_level_required: SecurityLevel = SecurityLevel.L1_LOW_WRITE
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SecurityIncidentReport(BaseModel):
    """Incident report generated by the SecOps agent."""
    incident_id: str
    threat_level: str = Field(description="LOW, MEDIUM, HIGH, CRITICAL")
    attacker_ip: str
    attack_type: str = Field(description="SSH Brute Force, Web Fuzzing, Port Scan, Rate Limit Abuse")
    evidence: List[str] = Field(default_factory=list)
    action_taken: str = Field(description="QUARANTINED_OPNSENSE, REPORTED, IGNORED")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SubAgentResult(BaseModel):
    """Result returned by a specialized sub-agent."""
    task_id: str
    role: AgentRole
    success: bool
    summary: str
    actions_executed: List[Dict[str, Any]] = Field(default_factory=list)
    metrics: Dict[str, Any] = Field(default_factory=dict)
    incident_report: Optional[SecurityIncidentReport] = None
    completed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
